### PR TITLE
sets -e explicitly in all the scripts in node

### PR DESCRIPTION
**Pull request by jatindogra**
https://github.com/Shippable/node/issues/282
https://github.com/Shippable/node/issues/286
https://github.com/Shippable/node/issues/285
https://github.com/Shippable/node/issues/284
image

### CODE REVIEW

**Comment by ric03uec** [comment]
why is the -e option on the top not sufficient?

**Comment by jatindogra** [comment]
It is getting overridden from the init script that calls this file.

**Comment by ric03uec** [comment]
i don't get it. which init script is calling this file? and irrespective of who is calling this file, the -e flag defined in this script should take precedence over any caller. If the first line is not working, why/how is this change working correctly?

**Comment by jatindogra** [comment]
The init script that we manually generate while creating the cluster node.

In that script initialize function calls
```
 exec_cmd "/bin/bash $NODE_SCRIPTS_LOCATION/$NODE_SCRIPTS_SUB_DIR/$NODE_ARCHITECTURE/$NODE_OPERATING_SYSTEM/boot.sh"
```
This overrides the -e flag. If any errors occurs it is not stopping the script. So we need to set -e, which is erroring out and stopping the script.

**Pull request merged**
